# Initial Data Understanding

## Loading Data and Libraries

In [1]:
import pandas as pd
import numpy as np
import sys
import os

import seaborn as sns
import matplotlib.pyplot as plt

sys.path.append('../src/')
pd.set_option('display.max_columns', None)

%matplotlib inline
%load_ext autoreload
%autoreload 2

## Análise preliminar dos dados de Quimioterapia e Radioterapia para Câncer de Mama
Neste documento serão tratadas as primeiras identificações de padrão e possíveis incongruências - de acordo com o julgamento do grupo - em relação aos dados fornecidos para Quimioterapia e Radioterapia de pacientes atendidos para câncer de mama.

In [5]:
kwargs = {'encoding':'latin-1', 'error_bad_lines':False, 'sep':',', 'low_memory':False, 'index_col':0, 'skiprows':0}

df_mama_quim = pd.DataFrame()
for chunk in pd.read_csv('../data/raw/Mama Quimioterapia SIA-SUS.zip', chunksize=100000, **kwargs):
    df_mama_quim = pd.concat([df_mama_quim, chunk], ignore_index=True)

df_mama_rad = pd.read_csv('../data/raw/Mama Radioterapia SIA-SUS.csv', **kwargs)

b'Skipping line 100354: expected 74 fields, saw 87\n'

In [7]:
import constants

df_mama_quim.rename(columns=constants.LAYOUT_APAC, inplace=True)
df_mama_rad.rename(columns=constants.LAYOUT_APAC, inplace=True)

### Amostras de dados
Um primeiro panorama de formatos e disposição de ambos datasets.

In [10]:
df_mama_quim.sample(5)

,dt_process,tp_gestao,cod_tp_gestao,cod_est_cnes,num_apac,dt_atend_paciente,proc_princ_apac,vl_tot_apac_aprov,cod_uf_mun,tp_est,tip_prest,est_man_ind,cnpj_est_exe,cnpj_mante,num_csn,cod_idade,num_idade,sexo,raca_cor,cod_uf_mun_paciente,nac_paciente,cep_paciente,uf_res_dif_paciente,mun_res_dif_paciente,dt_ini_val,dt_fim_val,tp_atend_apac,ind_apac,mot_sai_perm,ind_obito,ind_encerr,ind_perm,ind_alta,ind_transf,dt_ocorr,cod_org_emi,car_atend,num_apac_ant,cod_soli_cnes,dt_soli,dt_auto,cid_caus_assoc,cid_princ,cid_sec,etnia,aq_cid_10,aq_linfo_reg_inva,aq_estadi,aq_grahis,aq_dt_inden_pato,aq_trat_anter,aq_cidini1,aq_dt_ini_1_trat,aq_cidini2,aq_dt_ini_2_trat,aq_cidini3,aq_dt_ini_3_trat,aq_cont_trat,aq_dt_inic_trat_soli,aq_esqu_p1,aq_tot_mes_plan,aq_tot_mes_aut,aq_esu_p2
1588833,201506,EP,260000,582,2615205050238,201506,304050121,79.75,261160,7,61,M,1.089499e+13,1.089499e+13,{{|}{{|},4,46,F,3,260460,10,55940000,0,1,20150617,20150831,3,1,21,0,0,1,0,0,NaN,E260000001,1,NaN,582,20150617.0,2.01506e+07,0,C50- Câncer de Mama,0000,NaN,C501,S,2,00,20140514,S,C501,20140707.0,NaN,0.0,NaN,0.0,N,20141222,TMX,60,6,NaN
7594970,201812,PG,354870,2025361,3518255143580,201812,304050113,79.75,354870,5,0,M,4.652324e+13,4.652324e+13,{{{{}~~~,4,86,F,1,354870,10,9854530,0,1,20181101,20190131,3,2,21,0,0,1,0,0,NaN,M354870001,1,0,0,20181101.0,2.01811e+07,0000,C50- Câncer de Mama,0000,NaN,NaN,3,3,2,20180402,N,NaN,NaN,NaN,NaN,NaN,NaN,N,20180521,ARIMI,100,6,DEX
6768711,201701,EP,350000,2755130,3516242800829,201701,304050121,79.75,354140,5,0,M,4.637450e+13,4.637450e+13,}{~{}{{{{{~,4,52,F,1,351440,10,17900000,0,1,20161206,20170228,3,2,21,0,0,1,0,0,NaN,E350000016,1,0,2755130,20161206.0,2.01612e+07,0000,C50- Câncer de Mama,0000,NaN,NaN,N,2,0,20131217,N,NaN,NaN,NaN,NaN,NaN,NaN,S,20140324,TAMOX,6,0,IFENO
6888775,201704,PG,350320,2082527,3517215967034,201704,304020338,301.50,350320,5,0,I,4.396493e+13,0.000000e+00,}{|{{{|,4,74,F,1,355270,10,14910000,0,1,20170301,20170531,3,2,21,0,0,1,0,0,NaN,M350320008,1,0,0,20170301.0,2.01703e+07,0000,C50- Câncer de Mama,0000,NaN,NaN,S,3,G3,20150318,N,NaN,NaN,NaN,NaN,NaN,NaN,S,20170309,ANAST,3,3,ROZOL 1MG
4661707,201803,PG,230440,2723220,2318200051915,201802,304050075,800.00,230440,7,0,I,7.265515e+12,0.000000e+00,{{{|~}},4,46,F,1,230440,10,60441145,0,1,20180119,20180331,3,2,21,0,0,1,0,0,NaN,M230440001,1,0,2.72322e+06,20180119.0,20180314,0000,C50- Câncer de Mama,0000,NaN,C501,N,2,10,20170627,N,NaN,NaN,NaN,NaN,NaN,NaN,N,20170728,Taxol,15,6,NaN

In [11]:
df_mama_rad.sample(5)

,dt_process,tp_gestao,cod_tp_gestao,cod_est_cnes,num_apac,dt_atend_paciente,proc_princ_apac,vl_tot_apac_aprov,cod_uf_mun,tp_est,tip_prest,est_man_ind,cnpj_est_exe,cnpj_mante,num_csn,cod_idade,num_idade,sexo,raca_cor,cod_uf_mun_paciente,nac_paciente,cep_paciente,uf_res_dif_paciente,mun_res_dif_paciente,dt_ini_val,dt_fim_val,tp_atend_apac,ind_apac,mot_sai_perm,ind_obito,ind_encerr,ind_perm,ind_alta,ind_transf,dt_ocorr,cod_org_emi,car_atend,num_apac_ant,cod_soli_cnes,dt_soli,dt_auto,cid_caus_assoc,cid_princ,cid_sec,etnia,ar_smrd,ar_cid_10,ar_linfo_reg_inva,ar_estadi,ar_grahis,ar_dt_inden_pato,ar_trat_anter,ar_cidini1,ar_dt_ini_1_trat,ar_cidini2,ar_dt_ini_2_trat,ar_cidini3,ar_dt_ini_3_trat,ar_cont_trat,ar_dt_inic_trat_soli,ar_finalid_trat,ar_cid_topo_1,ar_cid_topo_2,ar_cid_topo_3,ar_num_ins_1,ar_dt_ini_1,ar_dt_ini_2,ar_dt_ini_3,ar_dt_fim_1,ar_dt_fim_2,ar_dt_fim_3,ar_num_ins_2,ar_num_ins_3
69011,201510,PG,230440,2723190,2315201242618,201510,304010286,829,230440,21,20,I,7990336000198,NaN,{~{|}~}|,4,46,F,3,160030,10.0,68902080,1,1,20151006,20151231,4,1,21,0,0,1,0,0,NaN,M230440001,1,0000000000000,2723190.0,20151006,20151023.0,0000,C50- Câncer de mama,0000,NaN,NaN,NaN,S,3,G2,20141007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,20151006.0,4.0,C793,NaN,NaN,60.0,20151006.0,NaN,NaN,20151021.0,NaN,NaN,NaN,NaN
313582,201710,EP,260000,2430843,2617205685700,201710,304010090,778,261160,39,0,I,24404329000186,0.0,{}{~}~,4,81,F,3,261160,10.0,51240510,0,1,20171020,20171231,4,1,21,0,0,1,0,0,NaN,E260000001,1,0000000000000,2430843.0,20171020,20171030.0,0000,C50- Câncer de mama,C795,NaN,NaN,NaN,S,4,0,20031112,NaN,C508,20031105.0,NaN,NaN,NaN,NaN,N,20171020.0,3.0,C795,NaN,NaN,40.0,20171020.0,NaN,NaN,20171231.0,NaN,NaN,NaN,NaN
505247,201703,PG,431490,2237601,4317200826500,201703,304010294,2410,431490,5,0,I,87020517000120,0.0,{{~~}|,4,58,F,1,432160,10.0,95590000,0,1,20170201,20170430,4,2,18,0,0,0,1,0,20170327.0,M431490001,1,0000000000000,2237601.0,20170201,20170201.0,0000,C50- Câncer de mama,0000,NaN,NaN,C508,N,1,03,20161223,N,NaN,0.0,NaN,00000000,NaN,0.0,N,20170201.0,2.0,C508,NaN,NaN,4.0,20170213.0,0.0,0.0,20170405.0,0.0,0.0,0.0,0.0
283689,201505,PG,250750,2399741,2515203154255,201505,304010286,1380,250750,7,61,I,9112236000194,NaN,{{|}~{{~~,4,63,F,1,250750,10.0,58057470,0,1,20150407,20150630,4,2,15,0,0,0,1,0,20150527.0,M250750701,1,0000000000000,2399741.0,20150407,20150407.0,0000,C50- Câncer de mama,0000,NaN,NaN,C509,S,3,2,20140903,S,C509,20141110.0,NaN,NaN,NaN,NaN,N,20150407.0,2.0,C509,NaN,NaN,5.0,20150407.0,NaN,NaN,20150630.0,NaN,NaN,0.0,0.0
548609,201706,PG,420540,19402,4217207697890,201706,304010294,4309,420540,5,0,I,83884999000106,0.0,{{{}{,4,38,F,1,421660,10.0,88122010,0,1,20170601,20170831,4,1,21,0,0,1,0,0,NaN,E420000018,2,0000000000000,19402.0,20170601,20170601.0,0000,C50- Câncer de mama,C770,NaN,NaN,NaN,N,3,8,20160802,N,NaN,NaN,NaN,NaN,NaN,NaN,N,20170601.0,2.0,C508,C770,NaN,120.0,20170601.0,20170601.0,NaN,20170831.0,20170831.0,NaN,40.0,NaN

### Geração de reports
Mesmo com análises exaustivas de frações dos dados, um overview total - de correlações, missing values et al - é imprescindível. Utilizando `pandas_profiling`, geraremos então relatórios que servirão de insumo do cenário macro desses dados.

In [12]:
from pandas_profiling import ProfileReport

ProfileReport(df_mama_quim).to_file('mama_quimioterapia_report.html')
ProfileReport(df_mama_rad).to_file('mama_radioterapia_report.html')

### Missing values

Devemos nos atentar ao valor informativo das colunas - porcentagens muito altas de missing values são indicativos de inaplicabilidade ou simplesmente não preenchimento da informação.

Primeiramente, nos dados de quimioterapia:

In [13]:
1 - df_mama_quim.count().sort_values().head(20) / len(df_mama_quim)

etnia               9.999218e-01
dt_ocorr            9.528107e-01
aq_cidini3          8.628335e-01
aq_dt_ini_3_trat    7.882332e-01
aq_cidini2          6.924594e-01
aq_cid_10           6.557957e-01
aq_dt_ini_2_trat    6.094069e-01
aq_cidini1          5.256917e-01
aq_dt_ini_1_trat    4.361935e-01
aq_esu_p2           3.426492e-01
cnpj_mante          2.748707e-01
num_apac_ant        9.078679e-02
dt_auto             6.386993e-02
dt_soli             3.932044e-02
cod_soli_cnes       4.795415e-03
aq_grahis           7.011300e-05
cnpj_est_exe        1.347321e-05
nac_paciente        5.624737e-06
aq_esqu_p1          2.616157e-07
aq_estadi           0.000000e+00
dtype: float64

A porcentagem de valores faltantes em `etnia` é certamente alarmante, uma coluna praticamente 100% nula. Vejamos seus poucos não-nulos

In [14]:
len(df_mama_quim[~df_mama_quim.etnia.isnull()]), len(df_mama_quim)

(598, 7644802)

Dado o volume de dados não contemplados por `etnia`, decidimos removê-la

In [16]:
df_mama_quim = df_mama_quim.drop(columns=['etnia'])

Seguidamente, nos dados de radioterapia:

In [15]:
1 - df_mama_rad.count().sort_values().head(20) / len(df_mama_rad)

ar_smrd             0.999997
etnia               0.999952
ar_cid_topo_3       0.973493
ar_dt_fim_3         0.963878
ar_dt_ini_3         0.963878
ar_cidini3          0.950476
ar_dt_ini_3_trat    0.902733
ar_cid_topo_2       0.808125
ar_dt_fim_2         0.799959
ar_dt_ini_2         0.799959
ar_cidini2          0.798322
ar_dt_ini_2_trat    0.750891
dt_ocorr            0.639168
ar_cidini1          0.622333
ar_num_ins_3        0.599192
ar_dt_ini_1_trat    0.573580
ar_num_ins_2        0.501368
ar_cid_10           0.482883
cnpj_mante          0.339376
ar_trat_anter       0.313292
dtype: float64

O cenário de 99.9%+ nulos observados em `etnia` se repetem também aqui, porém a `ar_smrd` - que inclusive não possui descrição no dicionário correlato - se apresenta com absolutos 100%. Iremos portanto descartar esta coluna.

In [17]:
df_mama_rad = df_mama_rad.drop(columns=['etnia', 'ar_smrd'])

### Valores constantes

De modo similar a missing values, colunas com valores constantes também não apresentam valor significativo. A partir do relatório, notamos essa característica no **Tipo de Atendimento APAC** para ambos sets.

In [18]:
df_mama_quim.tp_atend_apac.unique()

array([3], dtype=int64)

In [19]:
df_mama_rad.tp_atend_apac.unique()

array([4, 0], dtype=int64)

In [24]:
df_mama_rad[df_mama_rad.tp_atend_apac == 0]

,dt_process,tp_gestao,cod_tp_gestao,cod_est_cnes,num_apac,dt_atend_paciente,proc_princ_apac,vl_tot_apac_aprov,cod_uf_mun,tp_est,tip_prest,est_man_ind,cnpj_est_exe,cnpj_mante,num_csn,cod_idade,num_idade,sexo,raca_cor,cod_uf_mun_paciente,nac_paciente,cep_paciente,uf_res_dif_paciente,mun_res_dif_paciente,dt_ini_val,dt_fim_val,tp_atend_apac,ind_apac,mot_sai_perm,ind_obito,ind_encerr,ind_perm,ind_alta,ind_transf,dt_ocorr,cod_org_emi,car_atend,num_apac_ant,cod_soli_cnes,dt_soli,dt_auto,cid_caus_assoc,cid_princ,cid_sec,ar_cid_10,ar_linfo_reg_inva,ar_estadi,ar_grahis,ar_dt_inden_pato,ar_trat_anter,ar_cidini1,ar_dt_ini_1_trat,ar_cidini2,ar_dt_ini_2_trat,ar_cidini3,ar_dt_ini_3_trat,ar_cont_trat,ar_dt_inic_trat_soli,ar_finalid_trat,ar_cid_topo_1,ar_cid_topo_2,ar_cid_topo_3,ar_num_ins_1,ar_dt_ini_1,ar_dt_ini_2,ar_dt_ini_3,ar_dt_fim_1,ar_dt_fim_2,ar_dt_fim_3,ar_num_ins_2,ar_num_ins_3
168064,201505,MN,313130,2205440,3115233123486,201505,304010286,731,313130,5,61,M,19878404000100,1.987840e+13,{{}||~||,4,54,010,37558000,0,1.0,20151013,20151231,4,2,51,0,1,0,0,0,20151209,E310000010,1,NaN,2127989,20151010,20151010,0.0,C50- Câncer de mama,0.0,NaN,NaN,C509,2,20141216,N,C509,20151013,NaN,NaN,NaN,NaN,N,20151013,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Portanto, serão desconsideradas como colunas.

In [25]:
df_mama_quim = df_mama_quim.drop(columns=['tp_atend_apac'])
df_mama_rad = df_mama_rad.drop(columns=['tp_atend_apac'])

### Agrupamento de datas
Diversas colunas em ambos sets são marcações de tempo, que podem ajudar a inferir a duração dum tratamento.

Como primeiro passo para tratá-las, devemos convertê-las ao formato `datetime`.

In [26]:
dtcols = [c for c in df_mama_quim.columns if c.startswith('dt_')]
df_mama_quim[dtcols].head(10)

,dt_process,dt_atend_paciente,dt_ini_val,dt_fim_val,dt_ocorr,dt_soli,dt_auto
0,201401,201401,20140106,20140331,NaN,20140106.0,20140106
1,201401,201401,20140106,20140331,NaN,20140106.0,20140106
2,201401,201401,20140106,20140331,NaN,20140106.0,20140106
3,201401,201401,20131203,20140228,NaN,20131203.0,20131203
4,201401,201401,20140106,20140331,NaN,20140106.0,20140106
5,201401,201401,20131105,20140131,NaN,20131105.0,20131105
6,201401,201401,20131203,20140228,NaN,20131203.0,20131203
7,201401,201401,20140106,20140331,NaN,20140106.0,20140106
8,201401,201401,20131105,20140131,NaN,20131105.0,20131105
9,201401,201401,20131129,20140131,NaN,20131129.0,20131129

In [27]:
df_mama_quim[dtcols].dtypes

dt_process             int64
dt_atend_paciente      int64
dt_ini_val             int64
dt_fim_val             int64
dt_ocorr             float64
dt_soli              float64
dt_auto               object
dtype: object

As duas primeiras colunas - mês de processamento e atendimento ao paciente - formatam-se em ano-mês, portanto terão conversão diferenciada

In [28]:
ymth_dt = dtcols[0:2]
to_year_month = lambda df: df.apply(pd.to_datetime, format='%Y%M').apply(lambda date: date.to_period('M'))

In [238]:
df_mama_quim[ymth_dt] = df_mama_quim[ymth_dt].apply(to_year_month)
df_mama_rad[ymth_dt] = df_mama_rad[ymth_dt].apply(to_year_month)

df_mama_quim[ymth_dt].head(5)

   dt_process dt_atend_paciente
4     2014-01           2014-01
25    2014-01           2014-01
27    2014-01           2014-01
28    2014-01           2014-01
32    2014-01           2014-01

Nota-se que `dt_soli` (data de solicitação) e `dt_ocorr` (data de ocorrência) são colunas `float`, portanto contando com casas decimais que não fazem sentido para o formato `Y-M-d`.

In [271]:
ymd_dt = dtcols[2:-1]
# Retirada de casas decimais e conversão para datetime
str_to_date = lambda date: np.nan if pd.isnull(date) or len(date) != 8 else pd.to_datetime(date, format='%Y%m%d')

float_to_ymd = lambda df: df.fillna(0).astype(int).astype(str).replace('0', np.nan).apply(str_to_date)

In [275]:
df_mama_quim[ymd_dt] = df_mama_quim[ymd_dt].apply(float_to_ymd)
df_mama_rad[ymd_dt] = df_mama_rad[ymd_dt].apply(float_to_ymd)

df_mama_quim[ymd_dt].head(5)

   dt_ini_val dt_fim_val dt_ocorr    dt_soli
4  2013-11-05 2014-01-31      NaT 2013-11-05
25 2013-11-05 2014-01-31      NaT 2013-11-05
27 2013-11-05 2014-01-31      NaT 2013-11-05
28 2013-11-05 2014-01-31      NaT 2013-11-05
32 2013-11-28 2014-01-31      NaT 2013-11-28

In [ ]:
# Salva os arquivos preprocessados
df_mama_quim.to_csv('../data/raw/preprocessed/mama_quim_sia_sus.csv')
df_mama_rad.to_csv('../data/raw/preprocessed/mama_rad_sia_sus.csv')